version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - APP_ENV=dev
        volumes:
            - ./:/var/www/html
